apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: migadapter
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzakNDQWNZQ0NRRExOT2R6VldqdDZqQU5CZ2txaGtpRzl3MEJBUXNGQURBeE1Rc3dDUVlEVlFRR0V3SkIKVlRFaU1DQUdBMVVFQXd3WmMybHRjR3hsTFd0MVltVnlibVYwWlhNdGQyVmlhRzl2YXpBZUZ3MHlOREF6TURNeApOVFExTlRWYUZ3MHlOVEF6TURNeE5UUTFOVFZhTURFeEN6QUpCZ05WQkFZVEFrRlZNU0l3SUFZRFZRUUREQmx6CmFXMXdiR1V0YTNWaVpYSnVaWFJsY3kxM1pXSm9iMjlyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBcHNNdEQ2cG9BSmVLcnFjNk5FNTlzSjNFOG45enlRTFVPbERzOFpEQ2ltWHJINGJOWUNpYgo3NU1oaG1zRDR6ODYvcFZlYXZzTWJXMWp6TVpjQWs2QTJlZDhPVmxvcWh5YlUraW1lZm5kUXlJZG5yWWtiRy9uCllLN2RXSHhwUTNCNGQ2bk1kQU9Qd0xEZXUyUFY1ZmVpNjNEZHE4QkZzZU8yc3NFZzJsNGJKWGNXdUNKS3BHOUgKU3hhbEZURmNwMS9pSmYrcmduNHRqTUxKTjViOUlSOTY1VXNhM3VzWlpUTWFXalF0VVR4Smo4RTYzcW5KdHpkYwovWlZlamhlbWI2cENBbzdORlkzb3N3bE9WSkFVTkJCU3ZOSGxPa0ZEcWVXZTBRbjVrbzk4STVYcFVBNWkwei9tCm1DU0dSaHdGRmRySE1CWSt2eUg3KzFWTmZ6V0ZQUWVnSlFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFBWTB0Y3pZSENhQjJDc0toaGpNU2h4cVZUNS8zNjNCbldhSysvR1lKeTc3VmJ2aGtNL3RibFVVR0drNUJEQgo3OG5vaW5pb0prL2RXQjRUd2F6OUs1bXV6ZWJGa1l0aG9pU3RXMWczSkpzSkhBTEtYaSs2NGhBbnZ2eUY5aHdBCm5wcHpveWZUd0graGkxSUxGNDBJMVRYMWs4aU9lZEhlTUlKRC8rQ2drL1ZmRHpHS3lOQkZwd2V5Um9BMmNBcmcKYzFFYlZicmdrTVZKNGZ6Q3dqdEpJd3FpMWpSSm94MTZPcERuWnJ3VWd5aXdBZFc2YlFoZ1pudmx1RGZnV1dZSAovMitoeS9nSmNjVnhWQlR5ZVU1UVRsNXdWblVjZXlDVWlkWUN5K0tLdVhUM1MveDRsRDk2NlpRNnRzdC9FcDVNCmhrUWZGYXJnZkE5dWttTnFvNEtIejYzYwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://host:9443/mutate--v1-pod
  failurePolicy: Ignore
  name: mnvidiamigadapter.gpu.turbonomic.ibm.com
  rules:
  - apiGroups: [""]
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
