# permissions for end users to view nvidiamigadapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nvidiamigadapter-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: migadapter
    app.kubernetes.io/part-of: migadapter
    app.kubernetes.io/managed-by: kustomize
  name: nvidiamigadapter-viewer-role
rules:
- apiGroups:
  - gpu.turbonomic.ibm.com
  resources:
  - nvidiamigadapters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpu.turbonomic.ibm.com
  resources:
  - nvidiamigadapters/status
  verbs:
  - get
