---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - pods/finalizers
  verbs:
  - update
- resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gpu.turbonomic.ibm.com
  resources:
  - nvidiamigadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu.turbonomic.ibm.com
  resources:
  - nvidiamigadapters/finalizers
  verbs:
  - update
- apiGroups:
  - gpu.turbonomic.ibm.com
  resources:
  - nvidiamigadapters/status
  verbs:
  - get
  - patch
  - update
